Added parallel subproject. Fixed some typos.
bgenia/mmake pull request #3
Opened 2023-06-04 07:15 UTC by DiKetarogg

2023-06-04 08:00 UTC, bgenia requested changes

2023-06-04 08:00 UTC, bgenia commented on mmake.mk
> +MAKEFLAGS += -j
Эту строку лучше поднять наверх к остальной конфигурации мейка

2023-06-04 08:00 UTC, bgenia commented on mmake.mk
> +$(eval .PHONY: $1)
Чтоб избежать конфликтов именования я бы предложил добавить префикс целям для подпроектов, что думаешь?

2023-06-04 08:00 UTC, bgenia commented on mmake.mk
> +>	@:
Эта строчка точно нужна?

2023-06-04 08:00 UTC, bgenia commented on mmake.mk
> +))
Я бы такое форматирование предложил:
1) Лишние пробелы лучше не ставить даже если здесь они не важны. Кодовая база будет более однородной и снизится вероятность что случайно поставишь там где не надо.
2) Многострочный код для выполнения писать с новой строки, чтоб было нагляднее.
```suggestion
$(foreach p,$1,$(eval
$p:
>	$$(info Making subproject: $p)
>	$(MAKE) -C $(dir $p) -f $(notdir $p)
))
```
Ещё я здесь убрал `@`, зачем он?

2023-06-04 08:08 UTC, bgenia commented on mmake.mk
>  # TODO: Build subprojects in parallel
Вот это кстати убрать надо раз уж сделал

2023-06-04 08:08 UTC, DiKetarogg commented on mmake.mk
> +>	@:
Эта строчка нужна, чтобы не писалось nothing to be done for target.

2023-06-04 08:08 UTC, bgenia commented on mmake.mk
>  # TODO: Build subprojects in parallel
```suggestion
```

2023-06-04 08:14 UTC, DiKetarogg commented on mmake.mk
> +$(eval .PHONY: $1)
Имеет смысл, если ты планируешь сделать возможность генерировать множество мейкмейкфайлов и потом делать от них же зависимости.

2023-06-04 08:16 UTC, DiKetarogg commented on mmake.mk
> +))
@ нужно, чтобы не выводилась исполняемая команда. Если убрать, то будут сообщения типа `make -C ./ -f say_hi.mk`

2023-06-04 08:16 UTC, DiKetarogg commented on mmake.mk
>  # TODO: Build subprojects in parallel
Забыл :)

2023-06-04 08:17 UTC, bgenia commented on mmake.mk
> +))
А зачем не выводить команду? Она настолько сильно мешает? Мне всегда казалось что когда команды выводятся намного проще понимать что происходит

2023-06-04 09:18 UTC, DiKetarogg commented on mmake.mk
> +))
Не вижу смысла выводить команды. Если надо что-то выводить, то надо выводить прописанные логи, которые говорят что где происходит, исключительно релевантную информацию. Потому что потом искать где произошла ошибка с мусорными сообщениями команд тяжело. Я бы ещё убрал сообщения `make[1]: entering directory` если бы знал как.

2023-06-05 13:13 UTC, bgenia approved these changes

2023-06-05 13:13 UTC, merged